services:
  postgres:
    image: postgres:17-alpine
    container_name: vigiaenchente-db
    environment:
      POSTGRES_DB: vigiaenchente
      POSTGRES_USER: vigiaenchente
      POSTGRES_PASSWORD: vigiaenchente
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
